name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag rijojohn85-docker-react
      - name: Run test
        run: docker run -e CI=true rijojohn85-docker-react npm run test
